Feature/update resource page
pxblue/doc-it pull request #252
Opened 2020-09-14 17:28 UTC by emclaug2

#### Changes proposed in this Pull Request:
- Removes all old design pattern resources
- Adds links to new design pattern mono repos
- Add link to new react workflow package

#### Screenshots:
![image](https://user-images.githubusercontent.com/6538289/93118370-37ca1180-f68e-11ea-9780-5483161e8acf.png)

2020-09-14 17:30 UTC, emclaug2 commented
In the story it says that the new design pattern repos should be a single line instead of split into 4.  Since each item in the list links out to a demo, I wasn't sure how this should look visually.  I split the single item into 4.  

Is there a design for the single InfoListItem that links out to all 4 design pattern repos?

2020-09-14 17:38 UTC, joebochill commented
> In the story it says that the new design pattern mono repos should be condensed into a single line. Since each item in the list links out to a demo, I wasn't sure how this should look visually. I split the single item into 4.
> 
> Is there a design for the single InfoListItem that links out to all 4 design pattern repos?

Your interpretation is correct. I was expecting a single line item for each monorepo...not one for all four.

2020-09-14 18:06 UTC, joebochill submitted a review, later dismissed
- The live example buttons should link to CodeSandbox, StackBlitz, or Snack
- Should the github links point to the master branch instead of dev? The other packages do.

2020-09-15 15:08 UTC, emclaug2 commented
> * The live example buttons should link to CodeSandbox, StackBlitz, or Snack
> * Should the github links point to the master branch instead of dev? The other packages do.

I'll update the demo links to point directly to the demo and update the github link to point to master.

2020-09-15 17:06 UTC, emclaug2 commented
Since `ExampleRow` and `PackageRow`s were becoming very similar, I've merged these components into the `ResourceRow`.   This keeps the row generation logic a lot more streamlined imo.

2020-09-18 19:12 UTC, huayunh requested changes
Good job. Thanks, Evan!
* Why does ionic-design-pattern get displayed as a no-build?
* Code otherwise looks good

2020-09-18 19:12 UTC, huayunh commented on src/app/components/resources/ResourceRow.tsx
> +                            >{`@${version}`}</Typography>
This click lacks some discoverability... fine with it for now, but I'd prob refine the design (like add an npm icon on the right)

2020-09-18 22:58 UTC, emclaug2 commented on src/app/components/resources/ResourceRow.tsx
> +                            {name}
Good catch, I've just pushed out a fix for this.

2020-09-19 02:10 UTC, huayunh approved these changes

2020-09-19 02:11 UTC, merged